version: '3'

services:
  work:
    build: ./work
    volumes:
      - ${PROJECT_ROOT}:/var/www/html
    networks:
      - backend

  php-fpm:
    build: ./php-fpm
    volumes:
      - ${PROJECT_ROOT}:/var/www/html
      - ./php-fpm/log:/var/log/php/
    links:
      - "proxy:minio.${DOMAIN}"
    restart: on-failure
    networks:
      - backend

  redis:
    build: ./redis
    volumes:
      - redis_data:/data
    ports:
      - "${REDIS_PORT}:6379"
    restart: on-failure
    networks:
      - backend

  redis-commander:
    build: ./redis-commander
    restart: on-failure
    environment:
      - REDIS_HOSTS=local:redis:6379
    depends_on:
      - redis
    networks:
      - backend

  postgres:
    build: ./postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "${POSTGRES_PORT}:5432"
    restart: on-failure
    networks:
      - backend

  pgweb:
    build: ./pgweb
    depends_on:
      - postgres
    restart: on-failure
    networks:
      - backend

  mailhog:
    build: ./mailhog
    restart: on-failure
    volumes:
      - ./mailhog/inbox:/mailhog/inbox
    networks:
      - backend

  minio:
    build: ./minio
    volumes:
      - ./minio/data:/minio
    restart: on-failure
    networks:
      - backend

  nginx:
    build: ./nginx
    volumes:
      - ${PROJECT_ROOT}:/var/www/html
      - ./nginx/log:/var/log/nginx/
    restart: on-failure
    depends_on:
      - php-fpm
    networks:
      - backend

  proxy:
    build: ./proxy
    env_file:
      - .env
    volumes:
      - ./proxy/certificates:/ssl
      - ./proxy/log:/var/log/nginx/
    restart: on-failure
    ports:
      - "${HTTP_PORT}:80"
      - "${HTTPS_PORT}:443"
    networks:
      - frontend
      - backend

volumes:
  postgres_data:
  redis_data:

networks:
  frontend:
  backend:
