version: '3'

services:
  work:
    build: ./work
    volumes:
      - ${DOCKER_PROJECT_ROOT}:/var/www/html
    tty: true

  php-fpm:
    build: ./php-fpm
    volumes:
      - ${DOCKER_PROJECT_ROOT}:/var/www/html
    links:
      - "proxy:minio.${DOMAIN}"

  redis:
    build: ./redis
    volumes:
      - ./redis/data:/data
    ports:
      - "${REDIS_PORT}:6379"

  postgres:
    build: ./postgres
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
    ports:
      - "${POSTGRES_PORT}:5432"

  pgweb:
    build: ./pgweb
    depends_on:
      - postgres
    restart: on-failure

  mailhog:
    build: ./mailhog

  minio:
    build: ./minio
    volumes:
      - ./minio/data:/minio

  nginx:
    build: ./nginx
    volumes:
      - ${DOCKER_PROJECT_ROOT}:/var/www/html
      - ./nginx/log:/var/log/nginx/
    depends_on:
      - php-fpm

  proxy:
    build: ./proxy
    env_file:
      - .env
    volumes:
      - ./proxy/certificates:/ssl
      - ./proxy/log:/var/log/nginx/
    restart: on-failure
    ports:
      - "${HTTP_PORT}:80"
      - "${HTTPS_PORT}:443"
