version: '3'

services:
  work:
    build: ./work
    volumes:
      - ${PROJECT_ROOT}:/var/www/html

  php-fpm:
    build: ./php-fpm
    volumes:
      - ${PROJECT_ROOT}:/var/www/html
      - ./php-fpm/log:/var/log/php/
    links:
      - "proxy:minio.${DOMAIN}"
    restart: on-failure

  redis:
    build: ./redis
    volumes:
      - ./redis/data:/data
    ports:
      - "${REDIS_PORT}:6379"
    restart: on-failure

  postgres:
    build: ./postgres
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
    ports:
      - "${POSTGRES_PORT}:5432"
    restart: on-failure

  pgweb:
    build: ./pgweb
    depends_on:
      - postgres
    restart: on-failure

  mailhog:
    build: ./mailhog
    restart: on-failure

  minio:
    build: ./minio
    volumes:
      - ./minio/data:/minio
    restart: on-failure

  nginx:
    build: ./nginx
    volumes:
      - ${PROJECT_ROOT}:/var/www/html
      - ./nginx/log:/var/log/nginx/
    restart: on-failure

  proxy:
    build: ./proxy
    env_file:
      - .env
    volumes:
      - ./proxy/certificates:/ssl
      - ./proxy/log:/var/log/nginx/
    restart: on-failure
    ports:
      - "${HTTP_PORT}:80"
      - "${HTTPS_PORT}:443"
    depends_on:
      - pgweb
      - mailhog
      - minio
      - nginx
